#!/usr/bin/env node
/**
 * Sync the web app's local env from the monorepo-root .env.
 *
 * WHY THIS EXISTS: Turbopack inlines NEXT_PUBLIC_* into the CLIENT bundle from its OWN
 * native .env discovery, which only looks in the app directory — not the workspace root,
 * and not the next.config.ts env{} block (that proved unreliable for client inlining).
 * The root .env is our single source of truth (shared with the API service, isolation
 * rules documented in .env.example). So before dev/build we generate apps/web/.env.local
 * — which Next/Turbopack discover natively — from root .env.
 *
 * TWO CLASSES OF VAR, by Next's own rule (the prefix IS the firewall):
 *   - NEXT_PUBLIC_*  → inlined into the client bundle at build. Browser-readable.
 *   - everything else → server-only. Next NEVER ships an unprefixed var to the client;
 *     it is readable only in Node (Route Handlers, Server Components). This is enforced
 *     by Next, not by us.
 *
 * So this script copies the NEXT_PUBLIC_* set AND a SMALL, EXPLICIT ALLOWLIST of
 * server-only keys that the web app's OWN server runtime needs (currently just the
 * internal-call secret, for the server-side ingest Route Handler that calls the API's
 * internalProcedure). The allowlist is deliberate: secrets that belong ONLY to the API
 * service (service-role key, Google Places key) are NOT listed and never reach the web
 * app at all. Least authority — the web server gets exactly what it needs, nothing more.
 *
 * .env.local is gitignored (never committed); THIS generator is committed, so a fresh
 * clone runs `pnpm dev` and gets a correct .env.local automatically via the predev hook.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const appDir = resolve(here, "..");          // apps/web
const repoRoot = resolve(appDir, "../..");   // monorepo root
const rootEnvPath = resolve(repoRoot, ".env");
const outPath = resolve(appDir, ".env.local");

/**
 * Server-only keys the WEB app's server runtime legitimately needs. EXPLICIT allowlist,
 * not "everything non-public": keys that belong solely to the API service
 * (SUPABASE_SERVICE_ROLE_KEY, GOOGLE_PLACES_API_KEY_CORE) are intentionally absent so
 * they never reach the web app. Add a key here only when web server code actually needs it.
 */
const SERVER_ONLY_ALLOWLIST = new Set(["INTERNAL_CALL_SECRET"]);

let raw;
try {
  raw = readFileSync(rootEnvPath, "utf8");
} catch {
  console.warn(
    `[sync-env] No root .env at ${rootEnvPath}. Skipping .env.local generation. ` +
      `Copy .env.example to .env and fill it (see that file for the required keys).`,
  );
  process.exit(0); // don't block dev/build; the in-app error state will explain if unset
}

// Parse KEY=VALUE lines; keep NEXT_PUBLIC_* (client) + the server-only allowlist.
const publicLines = [];
const serverLines = [];
for (const line of raw.split("\n")) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith("#")) continue;
  const eq = trimmed.indexOf("=");
  if (eq === -1) continue;
  const key = trimmed.slice(0, eq).trim();
  const value = trimmed.slice(eq + 1).trim();
  if (key.startsWith("NEXT_PUBLIC_")) {
    publicLines.push(`${key}=${value}`);
  } else if (SERVER_ONLY_ALLOWLIST.has(key)) {
    serverLines.push(`${key}=${value}`);
  }
}

const header =
  "# GENERATED by scripts/sync-env.mjs from the monorepo-root .env — DO NOT EDIT.\n" +
  "# Edit the root .env instead; this file is regenerated before dev/build.\n" +
  "# NEXT_PUBLIC_* are client-inlined; the server-only block below is read ONLY in\n" +
  "# the Node runtime (Route Handlers) — Next never ships unprefixed vars to the client.\n";

const body =
  publicLines.join("\n") +
  "\n\n# --- server-only (NOT inlined to the client bundle; Node runtime only) ---\n" +
  serverLines.join("\n") +
  "\n";

writeFileSync(outPath, header + body, "utf8");
console.log(
  `[sync-env] Wrote ${publicLines.length} NEXT_PUBLIC_* + ${serverLines.length} server-only var(s) to apps/web/.env.local`,
);
