#!/usr/bin/env node
/**
 * Sync the web app's local env from the monorepo-root .env.
 *
 * WHY THIS EXISTS: Turbopack inlines NEXT_PUBLIC_* into the client bundle from its OWN
 * native .env discovery, which only looks in the app directory — not the workspace root,
 * and not the next.config.ts env{} block (that proved unreliable for client inlining).
 * The root .env is our single source of truth (shared with the API service, isolation
 * rules documented in .env.example). So before dev/build we generate apps/web/.env.local
 * — which Turbopack DOES discover natively — containing ONLY the NEXT_PUBLIC_* keys from
 * root .env. Server-only secrets (service-role key, internal secret) are deliberately
 * never copied here, so nothing secret can reach a client bundle.
 *
 * .env.local is gitignored (never committed); THIS generator is committed, so a fresh
 * clone runs `pnpm dev` and gets a correct .env.local automatically via the predev hook.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const appDir = resolve(here, "..");          // apps/web
const repoRoot = resolve(appDir, "../..");   // monorepo root
const rootEnvPath = resolve(repoRoot, ".env");
const outPath = resolve(appDir, ".env.local");

let raw;
try {
  raw = readFileSync(rootEnvPath, "utf8");
} catch {
  console.warn(
    `[sync-env] No root .env at ${rootEnvPath}. Skipping .env.local generation. ` +
      `Copy .env.example to .env and fill it (see that file for the required keys).`,
  );
  process.exit(0); // don't block dev/build; the in-app error state will explain if unset
}

// Parse KEY=VALUE lines, keep only NEXT_PUBLIC_* (the only vars the browser needs).
const publicLines = [];
for (const line of raw.split("\n")) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith("#")) continue;
  const eq = trimmed.indexOf("=");
  if (eq === -1) continue;
  const key = trimmed.slice(0, eq).trim();
  if (key.startsWith("NEXT_PUBLIC_")) {
    publicLines.push(`${key}=${trimmed.slice(eq + 1).trim()}`);
  }
}

const header =
  "# GENERATED by scripts/sync-env.mjs from the monorepo-root .env — DO NOT EDIT.\n" +
  "# Edit the root .env instead; this file is regenerated before dev/build.\n" +
  "# Contains ONLY NEXT_PUBLIC_* keys (browser-safe). Never holds server secrets.\n";

writeFileSync(outPath, header + publicLines.join("\n") + "\n", "utf8");
console.log(`[sync-env] Wrote ${publicLines.length} NEXT_PUBLIC_* var(s) to apps/web/.env.local`);
