#!/usr/bin/env node
/**
 * Sync the console app's local env from the monorepo-root .env. Identical in
 * mechanism to apps/web/scripts/sync-env.mjs: Turbopack inlines NEXT_PUBLIC_* from
 * its own .env discovery (app dir only), so before dev/build we generate
 * apps/console/.env.local containing ONLY the NEXT_PUBLIC_* keys from root .env.
 * Server-only secrets are never copied here. .env.local is gitignored; this
 * generator is committed so a fresh clone gets a correct .env.local via predev.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const appDir = resolve(here, "..");          // apps/console
const repoRoot = resolve(appDir, "../..");   // monorepo root
const rootEnvPath = resolve(repoRoot, ".env");
const outPath = resolve(appDir, ".env.local");

let raw;
try {
  raw = readFileSync(rootEnvPath, "utf8");
} catch {
  console.warn(
    `[sync-env] No root .env at ${rootEnvPath}. Skipping .env.local generation. ` +
      `Copy .env.example to .env and fill it (see that file for the required keys).`,
  );
  process.exit(0);
}

const publicLines = [];
for (const line of raw.split("\n")) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith("#")) continue;
  const eq = trimmed.indexOf("=");
  if (eq === -1) continue;
  const key = trimmed.slice(0, eq).trim();
  if (key.startsWith("NEXT_PUBLIC_")) {
    publicLines.push(`${key}=${trimmed.slice(eq + 1).trim()}`);
  }
}

const header =
  "# GENERATED by scripts/sync-env.mjs from the monorepo-root .env — DO NOT EDIT.\n" +
  "# Edit the root .env instead; this file is regenerated before dev/build.\n" +
  "# Contains ONLY NEXT_PUBLIC_* keys (browser-safe). Never holds server secrets.\n";

writeFileSync(outPath, header + publicLines.join("\n") + "\n", "utf8");
console.log(`[sync-env] Wrote ${publicLines.length} NEXT_PUBLIC_* var(s) to apps/console/.env.local`);
